"$schema" = 'https://starship.rs/config-schema.json'

# color scheme
# yellow #ffdfde
# blue #a48685
# red #c0303e
# organge #da4a52
# pink #c0303e
# purple #c0303e
# green #a48685
# aqua #a48685
# teal #a48685

format = """
[](#ffdfde)\
$os\
[](fg:#ffdfde bg:#a48685)\
$username\
[](fg:#a48685 bg:#c0303e)\
$directory\
[](fg:#c0303e bg:#c0303e)\
$git_branch\
$git_status\
[](fg:#c0303e bg:#a48685)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#a48685 bg:#a48685)\
$docker_context\
[](fg:#a48685 bg:#a48685)\
$time\
[ ](fg:#a48685)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#ffdfde fg:#240809"
format = "[ $symbol $path ]($style)"
disabled = false # Disabled by default

[os.symbols]
Arch = "󰣇"
Debian = ""
FreeBSD = ""
Linux = ""
Macos = ""
Windows = ""

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
# symbol = ""
style_user = "bg:#a48685"
style_root = "bg:#da4a52"
format = '[ $user ]($style)'
disabled = false

[directory]
style = "bold bg:#c0303e"
home_symbol = ""
format = "[ 󰉋 $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
# [directory.substitutions]
# "Documents" = "󰈙"
# "Downloads" = ""
# "Music" = ""
# "Pictures" = ""
# "aclu-emails" = "󱃜"

[git_branch]
symbol = "󰊢"
style = "bold bg:#c0303e"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bold bg:#c0303e"
format = '[$all_status$ahead_behind ]($style)'

[c]
symbol = ""
style = "bold bg:#a48685"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = ""
style = "bold bg:#a48685"
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = ""
style = "bold bg:#a48685"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = ""
style = "bold bg:#a48685"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = "󰟓"
style = "bold bg:#a48685"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bold bg:#a48685"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bold bg:#a48685"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bold bg:#a48685"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bold bg:#a48685"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "󰎙"
style = "bold bg:#a48685"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥"
style = "bold bg:#a48685"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = " bold bg:#a48685"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bold bg:#a48685"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "󰡨"
style = "bold bg:#a48685"
format = '[ $symbol $context ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bold bg:#a48685"
format = '[  $time ]($style)'
