# Espanso Match File
name: base
package_author: Pavel Sanchez
matches:
  - triggers: [";fn"]
    replace: "Pavel"

  - triggers: [";ln"]
    replace: "Sanchez"

  - triggers: [";fln"]
    replace: "Pavel Sanchez"

  - triggers: [";email", ";eml"]
    replace: "{{output}}"
    vars:
      - name: output
        type: choice
        params:
          values:
            - label: "Personal"
              id: "accounts@psanchez.me"
            - label: "Work"
              id: "psanchez@aclu.org"
            - label: "CAN Support"
              id: "cansupport@aclu.org"
            - label: "CAN Test"
              id: "cantest@aclu.org"
            - label: "Gmail Test"
              id: "aclucan.test@gmail.com"
            - label: "Litmus"
              id: "pavel@litmusemail.com"
            - label: "Seedlist"
              id: "seedlist-nat@aclu.org"
